### ISSUE TITLE
can't start calibration mode after shut down

### ISSUE THREAD

**Issue by hi-reeve** [AppHouseKitchen/AlDente-Charge-Limiter#833] opened 2022-11-25 02:55 UTC
**Describe the bug**
so i'm in the middle of calibration mode on discharge to 15% step, and i'm shut down my mac and turn it back on basically a hard restart.
when my mac start, aldente is still on discharge mode, but when i open the settings the calibration mode button is not activated. so i try to press the button but nothing happens.

**To Reproduce**
1. start calibration mode
2. wait until the discharge part (step 2)
3. shut down your mac
4. turn it back on 
5. open al dente settings

**Expected behavior**
calibration mode work normally

**Screenshots**
<img width="423" alt="image" src="https://user-images.githubusercontent.com/45350572/203890961-c9b29c2f-2dee-44f5-b2bb-0c821eca195a.png">
<img width="394" alt="image" src="https://user-images.githubusercontent.com/45350572/203890985-24c5b4c4-9370-4a4d-b6eb-08bc6e824fc8.png">

**MacBook (please complete the following information):**
 - MacBook model : MacBook m1 Pro 14 inch
 - macOS version Ventura
 - AlDente Pro or AlDente Free? Pro 
 - AlDente Version? 1.19.2
 - List of all enabled/disabled settings in AlDente:
 
<img width="420" alt="image" src="https://user-images.githubusercontent.com/45350572/203891071-3236ac7c-9a81-4558-b203-cd8a8f2ce5bf.png">
<img width="419" alt="image" src="https://user-images.githubusercontent.com/45350572/203891090-5802d02a-4e0f-4314-846e-55d2bf675997.png">
<img width="420" alt="image" src="https://user-images.githubusercontent.com/45350572/203891108-74937338-132e-4095-87c9-5f9b7f38d03c.png">
<img width="422" alt="image" src="https://user-images.githubusercontent.com/45350572/203891131-b92d32be-7444-4474-82ea-8fb6d9b792f6.png">

**Comment by zynth17** [comment] 2022-11-25 03:37
just in case you need the debug file.
[Uploading aldentepro-debug-2022-11-25-10:35:33.pasta.zip…]()

**Comment by MatthiasKerbl** [comment] 2023-01-12 13:44
Hi @zynth17,

In general, currently, the Calibration Mode is not meant to continue working after a restart. You need to restart the Calibration Mode again if you restart your MacBook.
Unfortunately, I am currently not able to reproduce your bug that the Calibration Mode does not work again after the restart. Are you still experiencing this issue with our newest version AlDente 1.20?

Cheers,
Matthias

**Comment by skrivanos** [comment] 2023-01-26 03:30
@MatthiasKerbl  I just experienced this with 1.20. Had a crash while discharging, then couldn't click start calibration again after boot. Clicking the button simply did nothing. Solved it by restarting AlDente a few more times and eventually it worked again.

On another note, please add a clearer button to toggle between the calibration steps or make the steps themselves clickable - took me a while to figure out.

**Comment by MatthiasKerbl** [comment] 2023-09-18 12:46
Hi @hi-reeve,

Noting the extended period since our last communication, I am proceeding to close this issue for the time being. Please remember that should you need to revisit this matter, don't hesitate to reach out. I'll be more than happy to reopen the issue and assist you further.

Best,
Matthias

**Closed by MatthiasKerbl** 2023-09-18 12:46 UTC
