### ISSUE TITLE
License Activation Failure Despite Stable Internet Connection

### ISSUE THREAD

**Issue by benkosa** [AppHouseKitchen/AlDente-Charge-Limiter#1179] opened 2024-02-28 16:39 UTC
**MacBook:**
 - MacBook Model: MacBook Pro 14-inch, 2021
 - macOS Version: Version 14.2.1 (23C71)
 - Charger Model:Third Party, 100w
 - Charging Cable:USB-C
 - AlDente Pro or AlDente Free:AlDente Free
 - AlDente Version: 1.25.2
 - Licence email: kelt.bestofshare@gmail.com
 - List or add screenshots of all enabled/disabled settings in AlDente:
![Screenshot 2024-02-28 at 17 03 34](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/17175794/5bf5a4c0-dd46-4fdf-881d-cf0eb566fc19)

**Describe the bug**
I am unable to activate my license despite having a stable internet connection.

**Expected Behavior**
The license should activate successfully with a stable internet connection.

**Screenshots and Screen Recordings**
![Screenshot 2024-02-28 at 16 59 21](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/17175794/952f8759-4636-4a86-94ff-644af5f2e4d3)
![Screenshot 2024-02-28 at 16 59 37](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/17175794/c7892c9a-a069-4312-ae68-ec3d3ac3666c)

**Debug file**
[aldentepro-debug-2024-02-28-17:04:40.pasta.txt](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/files/14437343/aldentepro-debug-2024-02-28-17.04.40.pasta.txt)

**Attempted Solutions**
Deactivate and attempted to reactivate the license, but it failed due to an error stating "unable to deactivate license."

**Comment by MatthiasKerbl** [comment] 2024-03-01 13:48
Hi @benkosa,

issues like that are usually caused by VPNs or Firewall apps such as Little Snitch or LuLu.
Do you have any VPNs or Firewalls running?
If yes, please allow AlDente to check the license.

Best,
Matthias

**Comment by MatthiasKerbl** [comment] 2024-06-18 12:58
Hi @benkosa,

Any updates on your issue?

Best,
Matthias

**Comment by MatthiasKerbl** [comment] 2024-08-12 07:36
Hi @benkosa,

It's been a while since we last heard from you, so I'm gonna go ahead and close this issue for now. If you need to come back to it later, just let me know. I'm here to help and can easily reopen it for you.

Best,
Matthias

**Closed by MatthiasKerbl** 2024-08-12 07:36 UTC
Labels: investigating
