### ISSUE TITLE
Allow Right-Click to be optional

### ISSUE THREAD

**Issue by jnnsrctr** [AppHouseKitchen/AlDente-Charge-Limiter#1127] opened 2023-12-15 11:53 UTC
As described in #1037, it is not super intuitive to have the right click directly perform an operation in the task bar.
It would be great to be able to disable this feature.

**Comment by MatthiasKerbl** [comment] 2023-12-16 15:17
Hi @jnnsrctr,

Thank you for your input, we will consider it in the future development of AlDente. Also, since this is a duplicate of #1037 I will close this issue. 

Best,
Matthias

**Closed by MatthiasKerbl** 2023-12-16 15:17 UTC
Labels: duplicate, enhancement
