### ISSUE TITLE
AlDente randomly stops working

### ISSUE THREAD

**Issue by Libroru** [AppHouseKitchen/AlDente-Charge-Limiter#1039] opened 2023-09-16 10:47 UTC
**Describe the bug**
It's been working fine for the first couple of days when I tested this, but then it randomly went over the 80% limit that I set once. Restarting the app seemed to help, but it's really annoying that I have to do that before every charge. 

**To Reproduce**
I guess it just happens randomly. There is no actual pattern that I could perceive.

**Expected behavior**
It charges to the charge limit and not over it. (Charge limit at 80% and it charges up to when I unplug the charger; So 90% is possible and has happened before).

**MacBook (please complete the following information):**
 - MacBook model: 13" M2 Macbook Air
 - macOS version: 13.4.1
 - AlDente Pro or AlDente Free? Free
 - AlDente Version? 1.22.2
 - List of all enabled/disabled settings in AlDente: The default free ones.

**Additional context**
Using it while the macbook is "sleeping", so closed display.

**Comment by MatthiasKerbl** [comment] 2023-09-16 16:23
Hi @Libroru,

We are sorry that you are experiencing this issue.
I think this is a duplicate of issue #922 and we have so far not been able to reproduce this issue.
Feel free to add any new findings to issue #922.

I will close this issue to keep everything regarding this bug tracked in one issue.

Best,

Matthias

**Closed by MatthiasKerbl** 2023-09-16 16:23 UTC
Labels: duplicate
