### ISSUE TITLE
Having Charge Limit at 70%, battery would ocasionally hit 71% and discharge for a couple of seconds

### ISSUE THREAD

**Issue by vladandrei51** [AppHouseKitchen/AlDente-Charge-Limiter#955] opened 2023-05-21 11:34 UTC
Pretty much the issue in the title.

This is especially annoying because it messes with the brightness when the discharge occurs. I didn't have this issue in the past.

Other possible relevant info:
Hardware Battery percentage on
Sailing mode 5% on
Heat Protection on/off makes no difference
Using AlDente Pro 1.21.4 & macOS Ventura 13.3.1 (a) on 13" MBP M1

**Comment by MatthiasKerbl** [comment] 2023-06-09 13:36
Hi @vladandrei51,

This is most likely caused by fluctuations in the battery percentage. When the battery percentage "jumps" to 71% due to the margin of error in the battery percentage, Automatic Discharge kicks in and discharges your MacBook down to 70% again. Unfortunately, there is not much that can be done to avoid this behavior. You could try to run the Calibration Mode to increase the accuracy of the battery percentage. If this issue still persists, consider turning off the Automatic Discharge feature.

Best,
Matthias

**Comment by MatthiasKerbl** [comment] 2023-11-14 08:19
Hi @vladandrei51,

Noting the extended period since our last communication, I am proceeding to close this issue for the time being. Please remember that should you need to revisit this matter, don't hesitate to reach out. I'll be more than happy to reopen the issue and assist you further.

Best,
Matthias

**Closed by MatthiasKerbl** 2023-11-14 08:19 UTC
