### ISSUE TITLE
Time remaining till battery depletion

### ISSUE THREAD

**Issue by FelixKLG** [AppHouseKitchen/AlDente-Charge-Limiter#1086] opened 2023-11-06 13:15 UTC
**Is your feature request related to a problem? Please describe.**
I've had 0 issues with AlDente since installing it, it has worked perfectly. I would however like a way to view the estimated time remaining from my charge from the menu bar pop-out like I can in iStat Util's battery monitor or via Activity Monitor.

**Describe the solution you'd like**
I'd like the estimated time remaining until my battery dies visible from the AlDente pop-out menu.

**Describe alternatives you've considered**
iStat or checking it from Activity Monitor.

**Additional context**
![CleanShot 2023-11-06 at 13 12 31@2x](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/44820580/ffc6fe89-e335-413a-bbe2-85d3e50ffa9f)
![CleanShot 2023-11-06 at 13 14 16@2x](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/44820580/02642c5a-8055-4d6d-8e08-b4511175a5f8)
![CleanShot 2023-11-06 at 13 14 55@2x](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/44820580/382784f7-e6f1-4ba3-be2e-830bde1c668a)

**Comment by DamonHD** [comment] 2023-11-06 13:19
Seconded.

Then I could stop using one of the other battery utilities I use!

Rgds

Damon

**Comment by TolleyLikesRice** [comment] 2023-11-07 22:03
More detailed duplicate of #1050 ?

Would be great though, then I wouldn't need to have the aldente icon hidden my bartender.

**Comment by MatthiasKerbl** [comment] 2023-11-09 17:23
Hi @FelixKLG,

Good idea, this is definitely something we will look into in one of the future updates. Also, since #1050 already mentions this, I will close this issue.

Best,
Matthias

**Closed by MatthiasKerbl** 2023-11-09 17:23 UTC

**Comment by jrhorne** [comment] 2024-01-15 20:24
@FelixKLG related question— has the iStat time remaining estimate been accurate while using AlDente? Was going to stick it into my menu bar but curious if it's been somewhat reliable
