### ISSUE TITLE
2015 Macbook Air 11" will no longer charge and boot once drained

### ISSUE THREAD

**Issue by ale-dd** [AppHouseKitchen/AlDente-Charge-Limiter#1130] opened 2023-12-17 02:26 UTC
**Describe the bug**
2015 Macbook Air 11" will no longer charge and boot once drained

**To Reproduce**
1. let the battery drain by unplugging the power
2. plug the power, wait for even days
3. attempt to power on
4. display shows a big empty battery with a red line to the left and a thunder underneat
5. open the bottom panel of the chassis
6. unplug the battery
7. power on with the battery unplugged
8. reset NVRAM
9. reset SMC
10. power off
11. replug the battery
12. power on and be back in business

**Expected behavior**
I would expect the laptop to be able to charge without having to reset NVRAM and SMC

**MacBook (please complete the following information):**
 - Apple MacBook Air "Core i7" 2.2 11" (Early 2015) [MacBookAir7,1] - [A1465]
 - Ventura via Opencore Legacy Patcher
 - This is the only laptop where I ran out of licenses, so it's on AlDente Free (as a matter of fact I would love if it were possible to transfer the license from another laptop that I no longer use)
 - unable to check more exact details until I'll reset the NVRAM/SMC and manage to charge

**Comment by MatthiasKerbl** [comment] 2023-12-18 13:19
Hi @ale-dd,

We are not sure if this behavior has anything to do with AlDente.
Did you try to reproduce this behavior when AlDente is uninstalled?

> This is the only laptop where I ran out of licenses, so it's on AlDente Free (as a matter of fact I would love if it were possible to transfer the license from another laptop that I no longer use)

That's possible without any issues, here is our FAQ for this:

What happens to my license when I get a new MacBook?
No worries, you can take your license to your new MacBook. Just deactivate your license on the old MacBook and activate it on your new one.

If you forgot to deactivate your license on your old MacBook, you need to contact the support team of our merchant of record Paddle at [assist@paddle.com.](mailto:assist@paddle.com)

Best,
Matthias

**Comment by MatthiasKerbl** [comment] 2024-01-23 14:32
Hi @ale-dd,

It's been a while since we last heard from you, so I'm gonna go ahead and close this issue for now. If you need to come back to it later, just let me know. I'm here to help and can easily reopen it for you.

Best,
Matthias

**Closed by MatthiasKerbl** 2024-01-23 14:32 UTC
