### ISSUE TITLE
The Power Flow Feature is buggy

### ISSUE THREAD

**Issue by PeppinoTech** [AppHouseKitchen/AlDente-Charge-Limiter#1246] opened 2024-06-20 06:03 UTC
**MacBook (please complete the following information):**
 - MacBook Model (https://support.apple.com/en-us/HT201608):MacBook Pro 13-inch,2020
 - macOS Version (https://support.apple.com/en-us/HT201260):Ventura 13.6.7 (22G720)
 - Charger Model (Apple, Third Party, Wattage,...):Third Party
 - Charging Cable (MagSafe 2, MagSafe 3, USB-C, Apple, Third Party,...):Third Party
 - AlDente Pro or AlDente Free:AlDente Pro
 - AlDente Version:1.26.1
 - List or add screenshots of all enabled/disabled settings in AlDente:
![CleanShot 2024-06-20 at 08 55 41](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/135860662/3db94e48-3105-482b-aa08-bf304871e42c)
![CleanShot 2024-06-20 at 08 58 38](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/135860662/9eecbc35-19e8-4075-97ee-56b309c59db8)
![CleanShot 2024-06-20 at 08 58 46](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/135860662/e74f92c0-6276-4a49-bfea-8258bba0ed92)
![CleanShot 2024-06-20 at 08 59 00](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/135860662/eb102572-fe37-4bc3-9fbb-ce1eb683bbc3)

 - Please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on How to generate and share a debug file on our blog(https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/).
 - External Monitor connected? iPad thru the cable
 - MacBook used in Clamshell Mode (with the lid closed)? no

**Describe the bug**
So.. The power flow thingy is buggy (you can see in the screen recording lower)

**To Reproduce**

**Expected Behavior**

**Screenshots and Screen Recordings**
If applicable, add screenshots or screen recordings of the issue to help explain your problem.

https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/135860662/e44049bb-e322-487a-9d0f-2fe21ab3260d

**Additional context**

**Comment by MatthiasKerbl** [comment] 2024-06-20 08:23
Hi @PeppinoTech,

I am sorry to hear that the Power Flow feature is not working as expected for you.
As a first step, please update to AlDente 1.27 which has many under-the-hood improvements. Afterward, if it still does not work, we will look deeper into your issue.

Best,
Matthias

**Comment by PeppinoTech** [comment] 2024-06-20 08:33
ok i'll try

**Comment by PeppinoTech** [comment] 2024-06-21 06:14
![CleanShot 2024-06-21 at 09 13 57](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/135860662/cf6dee14-3d02-4723-814b-dd68e915263f)
:\

**Comment by PeppinoTech** [comment] 2024-06-21 06:15
@MatthiasKerbl

**Comment by MatthiasKerbl** [comment] 2024-06-21 08:54
Hi @PeppinoTech,

I am sorry to hear that the Power Flow feature is still not working as intended for you.
Could you please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on How to generate and share a debug file on our blog(https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/).

Best,
Matthias

**Comment by MatthiasKerbl** [comment] 2024-08-12 07:43
Hi @PeppinoTech,

It's been a while since we last heard from you, so I'm gonna go ahead and close this issue for now. If you need to come back to it later, just let me know. I'm here to help and can easily reopen it for you.

Best,
Matthias

**Closed by MatthiasKerbl** 2024-08-12 07:43 UTC
Labels: bug, investigating

**Comment by PeppinoTech** [comment] 2024-08-12 07:46
Hi,@MatthiasKerbl. It's fixed btw I just really forgot about this issue lol
